import copy

BUILTIN_ARGS = {
    "log":["value"],
    "exit":["code"],
    "quit":["code"],
    "input":["prefix"],
    "clear":[],
    "cls":[],
    "istype":["value","type"],
    "list":[],
    "string":[],
    "range":["start","end","step"],
    "error":["name","description"],
    "len":["value"],
    "run":["filename"],
    "help":[],
    "String_replace":["string","old","new","count"],
    "String_toint":["string"],
    "String_tostring":["value"],
    "String_tofloat":["string"],
    "String_tolist":["string"],
    "String_empty":[],
    "String_split":["string","separator","count"],
    "String_lower":["string"],
    "String_upper":["string"],
    "String_title":["string"],
    "String_capitalize":["string"],
    "String_startswith":["string","prefix"],
    "String_endswith":["string","suffix"],
    "String_count":["string","substring"],
    "String_find":["string","substring"],
    "String_rfind":["string","substring"],
    "Float_toint":["float"],
    "Time_now":[],
    "Time_delta":["lasttime"],
    "File_read":["filename"],
    "File_write":["filename","content"],
    "File_remove":["filename"],
    "File_exists":["filename"],
    "File_listdir":["filename"],
    "List_add":["list","value"],
    "List_extend":["lista","listb"],
    "List_insert":["list","index","value"],
    "List_get":["list","index"],
    "List_set":["list","index","value"],
    "List_pop":["list","index"],
    "Math_round":["number","decimals"],
    "Math_floor":["number"],
    "Math_cos":["number"],
    "Math_sin":["number"],
    "Math_tan":["number"],
    "Math_acos":["number"],
    "Math_asin":["number"],
    "Math_atan":["number"],
    "Math_pow":["number","exponent"],
    "Math_factorial":["number"],
    "Math_degrees":["number"],
    "Math_radians":["number"],
    "Math_log":["number"],
    "Math_sqrt":["number"],
    "Random_randint":["rangea","rangeb"],
    "Random_randfloat":["rangea","rangeb"],
    "Random_choice":["list"],
}

REAL_BUILTIN_ARGS = copy.deepcopy(BUILTIN_ARGS)
for name in REAL_BUILTIN_ARGS.keys():
    if "_" in name:
        REAL_BUILTIN_ARGS[name].insert(0,"this")

BUILTIN_OBJS = {
    "String":["replace","toint","tostring","tofloat","tolist","empty","split","lower","upper","title","capitalize","find","rfind","count","startswith","endswith"],
    "Float":["toint"],
    "Time":["now","delta"],
    "File":["read","write","remove","exists","listdir"],
    "List":["add","extend","insert","get","set","pop"],
    "Math":["round","floor","cos","sin","tan","acos","asin","atan","pow","factorial","degrees","radians","log","sqrt"],
    "Random":["randint","randfloat","choice"]
    # Global: debug, exit, quit, clear, cls, istype, list, string, range, error, len, run, help
}